### PR TITLE
Extend AppCompatImageButton for compatibility

### PR DESCRIPTION
**Pull request by Jawnnypoo**
This way, people can use Vectors with Vector compatibility easily

### CODE REVIEW

**Comment by antorof** [comment]
+1

**Comment by Jawnnypoo** [comment]
Any thoughts on this @Clans ?

**Comment by FarbodSalamat-Zadeh** [comment]
Yes!! I am absolutely in support of this idea.

I have a project where I am using vector drawables on API 14+, but because this library doesn't support backwards compatibility with vector drawables yet, for now I am holding off from using it in my project.

I'm sure a lot of people would benefit from this idea too so I hope it gets merged soon...

**Review by KSas — APPROVED** [review]

**Comment by hannesa2** [comment]
This project is dead, I made at least a fork https://github.com/hannesa2/FloatingActionButton which

- builds on Travis
- using AppCombatXXX classes
- migrated to AndroidX


using it https://jitpack.io/#hannesa2/FloatingActionButton/2.0

If you have changes, please make a PR there and I merge it immediate

**Pull request closed without merging**
