### PR TITLE
Add FloatingActionMenu.getMenuButton() method

### PR DESCRIPTION
**Pull request by h6ah4i**
This PR adds `FloatingActionMenu.getMenuButton()` method.

```java
final FloatingActionButton menu = ...;

menu.getMenuButton().setOnClickListener(
    new View.OnClickListener {
         void onClick(View v) {
             // --- we can handle app specific actions here ---

             menu.toggle(true);
         }
    }
);
```

### CODE REVIEW

**Comment by h6ah4i** [comment]
Rebased. Please review and merge this PR.

**Comment by Clans** [comment]
What kind of specific actions we can handle with this that cannot be handled with the `OnMenuToggleListener`?

**Comment by h6ah4i** [comment]
@Clans Sorry for my late reply. I want to assign different actions to FloatingActionMenu's button  according to the state whether the menu is expanded or not. 

For instance, Google's Inbox app assigns "Compose" action when the menu is expanded. 

artboard 1

**Comment by gastoncesarf** [comment]
+1

**Pull request closed without merging**
