### PR TITLE
Support for Api 10

### PR DESCRIPTION
**Pull request by hamidrezabstn**
Add support for api 10 with nineoldandroids library

### CODE REVIEW

**Comment by hamidrezabstn** [comment]
hello ! please tell me why you closed it  ?

**Comment by Clans** [comment]
Hello, I don't plan to support API 10.

**Comment by hamidrezabstn** [comment]
thanks for your replay!

but can you tell me why ? you have a great library which is very useful !
it is better with backward compatibility

**Comment by Clans** [comment]
We need to let it go. ;)

**Comment by hamidrezabstn** [comment]
:))) i did'nt see that in this way! i agree and respect! ;)

**Pull request closed without merging**
